app/README.md
- README.md
- Create README.md file
[158422385](https://www.pivotaltracker.com/n/projects/2178749/stories/158422385)
N/A
N/A
=> Create README.md file

.gitignore, app/jest.config.json, app/package.json, app/src/tests/components/App.test.js, app/src/tests/setupTests.js
- setup unit test
- setup unit testing with jest and collect coverage reports
- run `npm test` for test and `npm run coverage` to run coverage reports.
[158422364](https://www.pivotaltracker.com/n/projects/2178749/stories/158422364)
N/A
N/A
=> Setup unit test

app/.eslintrc, hooks/applypatch-msg.sample, hooks/commit-msg, hooks/commit-msg.sample, hooks/post-update.sample, hooks/pre-applypatch.sample, hooks/pre-commit, hooks/pre-commit.sample, hooks/pre-push.sample, hooks/pre-rebase.sample, hooks/pre-receive.sample, hooks/prepare-commit-msg.sample, hooks/update.sample, package.json, setup_hooks.sh
**What does this PR do? **
This PR integrates pre-commit hooks, this is to enable code uniformity and code standard in the code base.
**Description of task completed?**
* Pre-commits hooks files
**How should this be manually tested?** 
* run yarn run dev
* make any change and try to commit
**Screenshort**
N/A
=> #158422151 Chore/setting up pre-commit hooks

package-lock.json, package.json
**What does this PR do? **
This PR fix git vulnerability issue
**Description of task completed?**
*updated boom
**How should this be manually tested?**
N/A
**Screenshort**
N/A
=> fix(vulnerability): Fix issue with git vulnerability

.env-sample, package-lock.json, src/config/index.js, src/index.html, src/index.js
- setup sentry for error logging
- setup sentry for error logging
- run `npm test` for test and `npm run coverage` to run coverage reports.
[158622711](https://www.pivotaltracker.com/n/projects/2178749/stories/158622711)
N/A
N/A
=> Setup sentry for error logging

client/package-lock.json, client/src/components/Order/Menus.jsx, client/src/components/Order/Orders.jsx, client/src/helpers/canOrderMeal.js, client/src/styles/components/_order.scss, src/helpers/canOrderMeal.js
- dynamically display dates on sidebar
- dynamically display dates on sidebar
- displays `No meals posted` when admin hasn't posted any meal yet
- run `npm test` for test and `npm run coverage` to run coverage reports.
[159069658](https://www.pivotaltracker.com/n/projects/2178749/stories/159069658)
N/A
=> Dynamically display Dates on Sidebar

.coveralls.yml, README.md, client/package-lock.json, client/package.json, client/src/components/Login/Login.jsx, client/src/tests/components/Login.test.js
**What does this PR do? **
This PR implements error display using react-toastify
**Description of task completed?**
* toastify added
* coveralls added
**How should this be manually tested? **
Login into the application using a none andela email
**Screenshort**
=> #159074060 feat/implemented toastify

.circleci/config.yml, .coveralls.yml, client/package-lock.json, client/package.json
**What does this PR do?**
fix the issue with coverall obtained badge
**Description of task completed?**
n/a
**Screenshot?**
n/a
=> #159074060 fix/coveralls issues

client/src/actions/ordersAction.js, client/src/components/Order/Orders.jsx, client/src/tests/components/Orders/Orders.test.js, client/yarn.lock
**What does this PR do?**
Pre-select the first meal date that for the user
**What are the relevant pivotal tracker stories?**
[#159196007](https://www.pivotaltracker.com/story/show/159196007)
**Screenshot?**
=> #159196007 Pre-select first orderable meal date

client/src/config/index.js
Updates staging url
-  updating staging url
N/A
=> Update Staging URL

client/package-lock.json, client/src/components/Order/Meal.jsx, client/src/components/Order/Menus.jsx, client/src/components/Order/Orders.jsx, client/src/tests/components/Orders/Orders.test.js
**What does this PR do?**
Fix Loader for the order page
**Description of Task to be completed?**
added a loading state
**How should this be manually tested?**
when the application is started using `npm run dev` you will see a loader displayed before the meal options returns
**What are the relevant pivotal tracker stories?**
159230197
**Any background context you want to add?**
N/A
**Screenshots**
=> fix/ implemented loader

client/src/components/Order/ConfirmOrder.jsx, client/src/components/Order/Orders.jsx, client/src/helpers/authorization.js, client/src/helpers/configAxios.js, client/src/helpers/logoutUser.js, client/src/styles/components/_navbar.scss
* Globally set JWT token in axios header [x-access-token] when user signs in to the app
* Remove the token from the app when user signs out
[159397737](https://www.pivotaltracker.com/story/show/159397737)
None
N/A
=> #159397737 Configure token in axios globally

client/src/components/Admin/Admin/Admin.jsx, client/src/components/App.jsx, client/src/components/common/Navbar/Navbar.jsx, client/src/components/common/Sidenav/Sidenav.jsx, client/src/helpers/authorization.js, client/src/styles/components/_navbar.scss, client/src/tests/components/common/SideNav.test.jsx, package-lock.json
- Create admin dashboard
- allow users with admin roles switch to the admin dashboard
- run `npm test` for test and `npm run coverage` to run coverage reports.
[160051953](https://www.pivotaltracker.com/n/projects/2178749/stories/160051953)
N/A
=> feat(dashboard): create admin dashboard

README.md, client/package-lock.json
**What does this PR do?**
- Updates README.md
**Description of Task to be completed?**
- Ensure README.md is up to date with the current app setup
**How should this be manually tested?**
- Clone this repo [here](https://github.com/andela/AndelaEatsUI.git)
-  `cd AndelaEatsUI` and checkout branch `ch-update-readme-160250773`
**Any background context you want to add?**
- N/A
**What are the relevant pivotal tracker stories?**
[#160250773](https://www.pivotaltracker.com/story/show/160250773)
=> #16025073 Update readme

client/package-lock.json, client/package.json, client/src/components/Admin/OrderHistory/ExportOrders.jsx, client/src/components/Admin/OrderHistory/OrdersHeader.jsx, client/webpack.common.js
- export orders
- admin should export orders made 24 hours ago
- Clone the repository [here](https://github.com/andela/AndelaEatsUI.git)
-  cd into AndelaEatsUI and checkout to this branch `ft-export-booked-orders-158527263`
- run these commands `npm run bundle` and `npm run dev` 
- Log in as an `Admin`, navigate to `admin dashboard`, select `Order History`, select `Export`, select `Download`.
- run the command `npm run test-dev` to ensure all tests are passing
- [158527263](https://www.pivotaltracker.com/n/projects/2178749/stories/158527263)
Nil
=> #158527263: Export order

client/src/actions/admin/mealItemsAction.js, client/src/actions/admin/menuItemsAction.js, client/src/components/Admin/Menus/Index.jsx, client/src/helpers/cloudinary.js, client/src/tests/actions/admin/mealItemsAction.test.js, client/src/tests/actions/admin/menuItemsAction.test.js, client/webpack.common.js, client/webpack.dev.js
Refactor menus and meal endpoints
- edit endpoints in menu action
- edit endpoints in meal action
- edit test
- Clone the repository [here](https://github.com/andela/AndelaEatsUI.git)
-  cd into AndelaEatsUI and checkout to this branch `ch-refactor-menu-meal-endpoint-161918348`
- run these commands `npm run bundle` and `npm run dev` 
- Log in as an `Admin`, navigate to `admin dashboard`, select `Menu Icon`, and click on `Add Menu`
- run the command `npm run test-dev` to ensure all tests are passing
- [161918348](https://www.pivotaltracker.com/n/projects/2178749/stories/161918348)
Nil
Nil
=> #161918348 Refactor menus and meal endpoints

client/webpack.common.js
=> bg(staging): fix staging issues

README.md
- add Code Climate's maintainability and CircleCI badges to the repo
- add Code Climate's maintainability and CircleCI badges to the repo
- Check out the repo at: [here...](https://github.com/andela/AndelaEatsUI)
- [#163356026](https://www.pivotaltracker.com/story/show/163356026)
=> #163356026 Add maintainability and CircleCI badges

client/src/actions/admin/menuItemsAction.js, client/src/components/Admin/Menus/Index.jsx, client/src/components/Admin/Menus/MenuModal.jsx, client/src/components/Admin/Menus/MenuTable.jsx, client/src/helpers/formatDropdown.js
- Fixes adding and editing a menu
- Filter engagement by its id, not vendor id
- Log into the application and navigate to the admin dashboard
- Add a menu or  edit an existing one.
- [#163818631](https://www.pivotaltracker.com/story/show/163818631)
N/A
N/A
=> #163818631 Fix adding and editing a menu 163818631

client/src/components/Admin/Meals/MealModal/Index.jsx
- Fixes editing a meal
- Ensure the right endpoint is called to edit a meal
- Log into the application and navigate to the admin dashboard
- Click on `Menus`, and navigate to the `Meals` tab.
- Edit any meal of your choice.
- [#163935058](https://www.pivotaltracker.com/story/show/163935058)
N/A
N/A
=> fix(edit-meal): fix editing a meal

client/src/index.js, client/src/styles/_globals.scss, client/src/styles/components/_ratings.scss, client/src/styles/components/admin/_engagements.scss, client/src/styles/components/admin/_menus.scss, client/src/styles/components/admin/_orders.scss, client/src/styles/components/admin/_vendors.scss
- Improve UI and solve reload issue on staging
- Make all options on list pages buttons
- Include hover effect on all rows of list pages
- Solve the reload issue on staging
- Clone the repository [here](https://github.com/andela/AndelaEatsUI.git)
-  cd into AndelaEatsUI and checkout to this branch `ch-improve-ui-164026017`
- run these commands `npm run build` and `npm run dev` 
- Log in as a user and navigate through the app.  You should now see changes made to the UI.
- [#164026017](https://www.pivotaltracker.com/story/show/164026017)
N/A
N/A
=> #164026017 Improve UI and solve reload issue on staging

client/package-lock.json, client/src/components/Order/Menus.jsx, client/src/components/common/Navbar/Navbar.jsx
- On the order page, removes all submenu items (if previously visible) whenever the reset button is clicked or a new date is selected.
- On the NavBar, reorders the Signout menu to be the last menu item on the list.
* Clone the repository [here](https://github.com/andela/AndelaEatsUI.git)
* cd into AndelaEatsUI and checkout to this branch `ui-fix`
* Run these commands `npm run build` and `npm run dev`
* Login to the platform 
-> select a date 
-> select main menu (side menu & protein menu shows up)
-> Reset your selection  or select another date.
-> The submenus (side menu & protein shouldn't be visible)
- [#164042403](https://www.pivotaltracker.com/story/show/164042403)
=> #164042403 Improve Order page UX

.circleci/config.yml, scripts/create_env.sh, scripts/deploy.sh
- Script to create a .env file in the applications root repository.
- Production  build of application requires that a `.env` file is available at the root of the repository with all the parameters.
- You can access the application working normally on:
> staging-eats.andela.com
- https://www.pivotaltracker.com/story/show/164668760
- N/A
N/A
=> Script to Create a .env file on Application Client Directory

client/.env.example
=> fix(env-creation): Initiate new build

client/.env.example
- [#story-id](pivotal-tracker-link)
=> Merge develop into master to initiate a new CCI build

client/package-lock.json
Fixes cloudinary spread bug by deleting package-lock.
- Pull branch
- Run `npm i`
- Run `npm run dev`
- The application should launch without any cloudinary spread error
- [#story-id](pivotal-tracker-link)
=> fix(cloudinary-bug): Fixes cloudinary spread error

README.md
- correct wrong spellings in the README.md file
- N/A
- Pull branch `ch-update-readme-165528326`
- Go through the README.md
- [#165528326](https://www.pivotaltracker.com/story/show/165528326)
- N/A
=> #165528326 update README.md

client/src/components/Dashboard/Dashboard.jsx, client/src/tests/components/dashboard/Dashboard.test.jsx
- Clears errors returned in the console when a user clicks dashboard.
- modify dashboard.jsx
- modify dashboard.test
- Run`git fetch` and `git checkout bg-clear-dashboard-console-error-165998875`
- Log in to the app
- Navigate to admin
- Click on the dashboard. The console should be clear.
- [ #165998875](https://www.pivotaltracker.com/story/show/165998875)
***Before fix***
***After fix***
=> #165998875 Clears console errors on dashboard

client/.eslintrc.json, client/src/actions/aboutAction.js, client/src/actions/admin/adminUserAction.js, client/src/actions/admin/engagementsAction.js, client/src/actions/admin/mealItemsAction.js, client/src/actions/admin/mealRatingActions.js, client/src/actions/admin/mealSessionsAction.js, client/src/actions/admin/menuItemsAction.js, client/src/actions/admin/ordersAction.js, client/src/actions/admin/suspendedVendorAction.js, client/src/actions/faqsAction.js, client/src/actions/ordersAction.js, client/src/actions/vendorsAction.js, client/src/components/EditOrder/EditOrder.jsx
Makes toastr messages more descriptive
* Make the toastr message after a successful edit of an order item more descriptive.
* Make the toastr message after successful addition of a new menu be more descriptive.
* Make the toastr message after successful addition of a new engagement more descriptive.
* Clone the repo and `cd` into the project directory
* Run `npm install` to install all project dependencies
* Run `npm run build && npm run dev` to start the app
* Try to successfully edit an order item
* Try to successfully add a new menu
* Try to successfully add a new engagement
[#166699006](https://www.pivotaltracker.com/story/show/166699006)
=> fix(make-messages-descriptive): make toastr messages more descriptive

README.md, client/.eslintrc.json, client/hooks/applypatch-msg, client/hooks/post-applypatch, client/hooks/post-checkout, client/hooks/post-commit, client/hooks/post-merge, client/hooks/post-receive, client/hooks/post-rewrite, client/hooks/post-update, client/hooks/pre-applypatch, client/hooks/pre-auto-gc, client/hooks/pre-commit, client/hooks/pre-push, client/hooks/pre-rebase, client/hooks/pre-receive, client/hooks/prepare-commit-msg, client/hooks/push-to-checkout, client/hooks/sendemail-validate, client/hooks/update, client/src/actions/admin/ordersAction.js, client/src/components/Admin/OrderHistory/Index.jsx, client/src/components/Admin/Vendors/Vendors.jsx, client/src/components/common/FormInputs.jsx, client/src/helpers/inputValidation.js, client/src/store/store.js, client/src/tests/components/Admin/Vendors/vendors.test.js, client/yarn.lock
Adds validation to the input form field when an admin adds a new vendor
* Add custom validation to phone number form field when an admin adds a new vendor
* Change package manager from NPM to Yarn
* Update ReadME file
* Run `yarn build && yarn dev` to start the app
* Login to the app and go to the admin dashboard
* Try to view the list of vendors and try to add a new vendor
* In the phone number form field used to add a new vendor, enter a non-digit and click `Add vendor`
* An error message will show, telling the admin that only digits are required.
- [#167271238](https://www.pivotaltracker.com/story/show/167271238)
=> #167271238 Add Validation to Input Form Field

client/src/components/Admin/Menus/MenuTemplate/AddMenuTemplate.js, client/src/components/Admin/Menus/MenuTemplate/index.js, client/src/components/App.jsx, client/src/components/common/FormInputs.jsx, client/src/components/common/Modal.jsx, client/src/components/common/Sidenav/Sidenav.jsx, client/src/styles/components/admin/_menuTemplate.scss, client/src/styles/main.scss, client/src/tests/__mocks__/selectMock.js, client/src/tests/components/Admin/Menus/MenuTemplate/index.test.js
- It creates a template for the create menu template feature
- Add AddMenuTemplate component
- Add MenuTemplate component
- Add MenuTemplate.scss
- Modify Sidenav to add the `Menu template` sub menu.
- Add tests
- `git fetch` and `git checkout` to this branch
- Log in to the application
- Navigate to admin, click on  `Manage Menus` and then `Menu Templates`.
- Click on the `Create` button. The add menu template modal will pop up.
- [#167647518](https://www.pivotaltracker.com/story/show/167647518)
=> #167647518 Create a  menu template template

client/package.json, client/src/components/Admin/Meals/Index.jsx, client/src/styles/components/admin/_meals.scss, client/src/tests/components/Admin/Meals/Index.test.jsx
It adds search functionality to meal items
- design search input
- add functionality to enable searching meal items
- Log into the application.
- Access the Admin Panel, navigate to the Manage Menus > Meals.
- Search for a meal.
- [#166352049](https://www.pivotaltracker.com/story/show/166352049)
Previously, it was not possible to search for a meal
=> #166352049 Add search functionality to meal items

client/src/actions/ordersAction.js, client/src/components/Admin/Menus/Index.jsx, client/src/components/Admin/Menus/MenuModal.jsx, client/src/components/MealCard/MealCard.jsx, client/src/components/MealCard/Modal.jsx, client/src/components/MealCard/NotCollectedAction.jsx, client/src/components/OrderHistory/OrderHistory.jsx, client/src/components/common/FormInputs.jsx, client/src/styles/components/admin/_menus.scss, client/src/tests/components/Admin/Menus/Index.test.js, client/src/tests/components/MealCard/MealCard.test.jsx, client/src/tests/components/OrderHistory/OrderHistory.test.jsx, client/src/tests/reducers/ordersReducer.test.js
Allows a user to rate an order successfully
* Ensure a user can rate a menu successfully
* Refactor the codebase as see fit
* Ensure all tests pass.
* Clone the repo and `cd` into the project's directory
* Run `npm install` to install dependencies
* Run `npm run build && npm run dev` to start the app
* Navigate to the `/orders` URL
* click on the `order` menu in the side Nav
* Click on the `Rate` button to rate a meal
[#166872563](https://www.pivotaltracker.com/story/show/166872563)
=> #166872563 User Should Rate an Order Successfully
